"""Execute exact Storyboard shots, without upstream reasoning or workflow writes."""
import hashlib
import json

from history_studio.models import (
    ArtifactReference, GenerationMetadata, GenerationMethod, MediaAssetReference,
    MediaType, StoryboardPackage, VisualAsset,
)
from history_studio.storage import ArtifactStore, MediaIntegrityError, MediaStore
from history_studio.models.base import Contract

from .image import ImageGenerationResult, ImageProvider
from .video import VideoGenerationResult, VideoProvider


class PersistedVisual(Contract):
    asset: MediaAssetReference
    metadata: GenerationMetadata


def _persist_image(result: ImageGenerationResult, *, digest: str, version: int,
                   intermediate: bool, media_store: MediaStore) -> tuple[MediaAssetReference, GenerationMetadata]:
    if not isinstance(result, ImageGenerationResult) or result.image_format != "png":
        raise ValueError("Image provider must return a PNG ImageGenerationResult")
    metadata = GenerationMetadata(provider=result.provider, model=result.model)
    if not isinstance(result.image_bytes, bytes) or not result.image_bytes:
        raise ValueError("Image provider must return non-empty image bytes")
    # The intermediate has its own immutable identity/path, separate from final
    # shot output. No second final VisualAsset or durable model expansion is needed.
    prefix = "img" if intermediate else "vis"
    role = "intermediate/" if intermediate else ""
    reference = media_store.save_bytes(asset_id=f"{prefix}-{digest}",
        relative_path=f"images/storyboard-v{version}/{role}{digest}.png",
        media_type=MediaType.IMAGE, data=result.image_bytes)
    reference = MediaAssetReference.model_validate(reference.model_dump(mode="json"))
    if reference.media_type != MediaType.IMAGE:
        raise ValueError("Stored image must have IMAGE media type")
    if media_store.read_bytes(reference) != result.image_bytes:
        raise MediaIntegrityError("Persisted image differs from generated bytes")
    return reference, metadata


def _persist_video(result: VideoGenerationResult, *, digest: str, version: int,
                   media_store: MediaStore) -> tuple[MediaAssetReference, GenerationMetadata]:
    if not isinstance(result, VideoGenerationResult) or result.video_format != "mp4":
        raise ValueError("Video provider must return an MP4 VideoGenerationResult")
    metadata = GenerationMetadata(provider=result.provider, model=result.model)
    if not isinstance(result.video_bytes, bytes) or not result.video_bytes:
        raise ValueError("Video provider must return non-empty video bytes")
    reference = media_store.save_bytes(asset_id=f"vis-{digest}",
        relative_path=f"video/storyboard-v{version}/{digest}.mp4",
        media_type=MediaType.VIDEO, data=result.video_bytes)
    reference = MediaAssetReference.model_validate(reference.model_dump(mode="json"))
    if reference.media_type != MediaType.VIDEO:
        raise ValueError("Stored video must have VIDEO media type")
    if media_store.read_bytes(reference) != result.video_bytes:
        raise MediaIntegrityError("Persisted video differs from generated bytes")
    return reference, metadata


def generate_visual_assets(*, storyboard_input_ref: ArtifactReference,
                           artifact_store: ArtifactStore, media_store: MediaStore,
                           image_provider: ImageProvider | None = None,
                           video_provider: VideoProvider | None = None, recovery=None) -> tuple[VisualAsset, ...]:
    """One final asset per exact shot in section/shot presentation order.

    Caller supplies the approved Storyboard reference; approval enforcement remains
    a workflow responsibility. Only that exact Storyboard is loaded, with no latest
    discovery or upstream semantic loads. Providers receive approved prompts only.
    V1 accepts declared PNG/MP4 non-empty bytes, not decoded frame/playback validation.
    MediaStore owns hashing, containment, immutable publication and exact reads.

    IMAGE_TO_VIDEO persists an intermediate PNG and reads verified persisted bytes
    before video generation. With recovery, each intermediate/final dispatch has
    separate durable evidence. Without it, retries regenerate and require identical
    bytes at immutable paths. Existing outputs are never discovered/adopted.
    Failures raise, leaving any successful earlier publications as orphan binaries.
    No partial successful tuple, manifest publication or workflow state mutation.
    """
    reference = ArtifactReference(project_id=storyboard_input_ref.project_id,
                                  artifact_type=storyboard_input_ref.artifact_type,
                                  version=storyboard_input_ref.version)
    if reference.artifact_type != "storyboard":
        raise ValueError("Visual generation requires an exact storyboard reference")
    if reference.project_id != artifact_store.project_dir.name:
        raise ValueError("Storyboard reference project must match artifact directory")
    storyboard = artifact_store.load("storyboard", reference.version, StoryboardPackage)
    storyboard = StoryboardPackage.model_validate(storyboard.model_dump(mode="json"))
    if storyboard.script_input_ref.project_id != reference.project_id:
        raise ValueError("Storyboard Script provenance belongs to a different project")
    shots = [shot for section in storyboard.sections for shot in section.shots]
    # Preflight all requirements before any generation; invalid later shots or a
    # missing provider cannot trigger an avoidable partially executed batch.
    methods = {shot.generation_method for shot in shots}
    if methods & {GenerationMethod.STATIC_IMAGE, GenerationMethod.IMAGE_TO_VIDEO} and image_provider is None:
        raise ValueError("Storyboard methods require an image provider")
    if methods & {GenerationMethod.TEXT_TO_VIDEO, GenerationMethod.IMAGE_TO_VIDEO} and video_provider is None:
        raise ValueError("Storyboard methods require a video provider")
    assets = []
    for shot in shots:
        identity = json.dumps([reference.model_dump(mode="json"), storyboard.script_input_ref.model_dump(mode="json"),
                               shot.shot_id], sort_keys=True, separators=(",", ":"))
        digest = hashlib.sha256(identity.encode("utf-8")).hexdigest()
        def persist(kind, intermediate, call, request):
            prefix = "img" if intermediate else "vis"
            expected_type = MediaType.IMAGE if kind == "image" else MediaType.VIDEO
            role = "intermediate/" if intermediate else ""
            expected_path = (f"images/storyboard-v{reference.version}/{role}{digest}.png" if kind == "image"
                             else f"video/storyboard-v{reference.version}/{digest}.mp4")
            def execute():
                if recovery is not None and (media_store.root / expected_path).exists():
                    raise ValueError("Unjournaled visual output cannot authorize another dispatch")
                result = call()
                if kind == "image":
                    asset, metadata = _persist_image(result, digest=digest, version=reference.version,
                                                    intermediate=intermediate, media_store=media_store)
                else:
                    asset, metadata = _persist_video(result, digest=digest, version=reference.version, media_store=media_store)
                return PersistedVisual(asset=asset, metadata=metadata)
            def validate(value):
                if (value.asset.asset_id != f"{prefix}-{digest}" or value.asset.relative_path != expected_path
                    or value.asset.media_type != expected_type):
                    raise ValueError("Recovered visual identity mismatch")
                provider = image_provider if kind == "image" else video_provider
                if getattr(provider, "model", value.metadata.model) != value.metadata.model:
                    raise ValueError("Recovered visual provider model mismatch")
                if not media_store.read_bytes(value.asset):
                    raise ValueError("Recovered visual must contain non-empty bytes")
            value = execute() if recovery is None else recovery.perform(
                key=f"{kind}:{'intermediate:' if intermediate else ''}{shot.shot_id}", request=request,
                result_type=PersistedVisual, execute=execute, validate=validate)
            return value.asset, value.metadata

        if shot.generation_method == GenerationMethod.STATIC_IMAGE:
            asset, metadata = persist("image", False, lambda: image_provider.generate(prompt=shot.generation_prompt),
                                      {"prompt": shot.generation_prompt, "method": "STATIC_IMAGE"})
        elif shot.generation_method == GenerationMethod.TEXT_TO_VIDEO:
            asset, metadata = persist("video", False, lambda: video_provider.generate_from_text(prompt=shot.generation_prompt),
                                      {"prompt": shot.generation_prompt, "method": "TEXT_TO_VIDEO"})
        elif shot.generation_method == GenerationMethod.IMAGE_TO_VIDEO:
            intermediate, _ = persist("image", True, lambda: image_provider.generate(prompt=shot.generation_prompt),
                                       {"prompt": shot.generation_prompt, "method": "IMAGE_TO_VIDEO_INTERMEDIATE"})
            image = media_store.read_bytes(intermediate)
            asset, metadata = persist("video", False,
                lambda: video_provider.generate_from_image(image=image, prompt=shot.generation_prompt),
                {"prompt": shot.generation_prompt, "method": "IMAGE_TO_VIDEO", "image_sha256": intermediate.sha256})
        else:
            raise ValueError(f"Unsupported generation method: {shot.generation_method}")
        assets.append(VisualAsset(shot_id=shot.shot_id, source_segment_id=shot.source_segment_id,
                                 asset=asset, generation_method=shot.generation_method,
                                 generation_metadata=metadata))
    return tuple(assets)
